mes: mayo # "enero", "febrero", "marzo", "abril", "mayo", "junio", "julio", "agosto", "septiembre", "octubre", "noviembre", "diciembre"
cantidad_guardias_a_generar: 20
dias_con_dos_medicos: ["martes", "jueves"] # "lunes", "martes", "miercoles", "jueves", "viernes", "sabado", "domingo"
medicos:
  - nombre: Juan
    peticiones:
      dias_sin_guardia: [] # "lunes", "martes", "miercoles", "jueves", "viernes", "sabado", "domingo"
      vacaciones:
        inicio: 0
        fin: 0
      dias_peticion: [1,4,7,8,28]
  - nombre: Ana
    peticiones:
      dias_sin_guardia: ["martes"]
      vacaciones:
        inicio: 0
        fin: 0
      dias_peticion: []
  - nombre: Diego
    peticiones:
      dias_sin_guardia: []
      vacaciones:
        inicio: 0
        fin: 0
      dias_peticion: []
  - nombre: Carlos
    peticiones:
      dias_sin_guardia: []
      vacaciones:
        inicio: 0
        fin: 0
      dias_peticion: []
  - nombre: Camilo
    peticiones:
      dias_sin_guardia: []
      vacaciones:
        inicio: 0
        fin: 0
      dias_peticion: []
  - nombre: Diana
    peticiones:
      dias_sin_guardia: []
      vacaciones:
        inicio: 0
        fin: 0
      dias_peticion: []
  - nombre: Jacinto
    peticiones:
      dias_sin_guardia: []
      vacaciones:
        inicio: 0
        fin: 0
      dias_peticion: []
  - nombre: Senen
    peticiones:
      dias_sin_guardia: []
      vacaciones:
        inicio: 0
        fin: 0
      dias_peticion: []
  - nombre: Santiago
    peticiones:
      dias_sin_guardia: []
      vacaciones:
        inicio: 0
        fin: 0
      dias_peticion: []
  - nombre: Fabio
    peticiones:
      dias_sin_guardia: []
      vacaciones:
        inicio: 0
        fin: 0
      dias_peticion: []
  - nombre: Hernan
    peticiones:
      dias_sin_guardia: []
      vacaciones:
        inicio: 0
        fin: 0
      dias_peticion: []